Asp net core support
SparkViewEngine/spark pull request #79
Opened 2024-04-19 16:45 UTC by bounav

- New csproj that targets .net 8.0
- Moved precompilation bits from the SparkViewFactory class to its own class
- H() method replaced with OutputValue(object value, bool automaticEncoding) in the base classes all generated views inherit from, this simplified the HTML encoding of values.

2024-04-23 09:38 UTC, RobertTheGrey requested changes
Looks good to me, but there seems to be a merge conflict?

2024-04-23 15:51 UTC, bounav commented
My bad. I fixed the conflict.

2024-04-23 15:52 UTC, bounav commented
> Looks good to me, but there seems to be a merge conflict?

My bad. I fixed the conflict.

2024-04-24 13:58 UTC, RobertTheGrey approved these changes

2024-04-24 13:58 UTC, merged